// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ArtistasColumns holds the columns for the "Artistas" table.
	ArtistasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "plays", Type: field.TypeInt64},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"f", "m"}},
	}
	// ArtistasTable holds the schema information for the "Artistas" table.
	ArtistasTable = &schema.Table{
		Name:        "Artistas",
		Columns:     ArtistasColumns,
		PrimaryKey:  []*schema.Column{ArtistasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SongsColumns holds the columns for the "songs" table.
	SongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeInt},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "plays", Type: field.TypeInt64},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"f", "m"}},
		{Name: "artist_songs", Type: field.TypeInt, Nullable: true},
	}
	// SongsTable holds the schema information for the "songs" table.
	SongsTable = &schema.Table{
		Name:       "songs",
		Columns:    SongsColumns,
		PrimaryKey: []*schema.Column{SongsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "songs_Artistas_songs",
				Columns: []*schema.Column{SongsColumns[5]},

				RefColumns: []*schema.Column{ArtistasColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArtistasTable,
		SongsTable,
	}
)

func init() {
	SongsTable.ForeignKeys[0].RefTable = ArtistasTable
}
