// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"enttest/ent/artist"
	"enttest/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ArtistDelete is the builder for deleting a Artist entity.
type ArtistDelete struct {
	config
	predicates []predicate.Artist
}

// Where adds a new predicate to the delete builder.
func (ad *ArtistDelete) Where(ps ...predicate.Artist) *ArtistDelete {
	ad.predicates = append(ad.predicates, ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *ArtistDelete) Exec(ctx context.Context) (int, error) {
	return ad.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *ArtistDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *ArtistDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: artist.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: artist.FieldID,
			},
		},
	}
	if ps := ad.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
}

// ArtistDeleteOne is the builder for deleting a single Artist entity.
type ArtistDeleteOne struct {
	ad *ArtistDelete
}

// Exec executes the deletion query.
func (ado *ArtistDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{artist.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *ArtistDeleteOne) ExecX(ctx context.Context) {
	ado.ad.ExecX(ctx)
}
